# Generated by Django 4.1.7 on 2023-03-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signuptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mobilenumber', models.BigIntegerField()),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
            ],
        ),
    ]
