# Generated by Django 4.1.7 on 2023-03-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('login_time', models.CharField(max_length=250)),
                ('logout_time', models.CharField(max_length=256)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
