# Generated by Django 4.1.7 on 2023-03-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0002_detailstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='salarytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(max_length=256)),
                ('date', models.DateField()),
            ],
        ),
    ]
