# Generated by Django 4.1.7 on 2023-03-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0004_alter_salarytable_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytable',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
